---
title: "Candidate_Filter"
author: "Michelle Liu"
date: "13/06/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyverse)
```


```{r}
Hardy <- data.frame(read_delim("~/Desktop/THESIS PR/New_Dups/missing_70.hwe", delim = "\t"))
Hardy
Freq <- data.frame(read_delim("~/Desktop/THESIS PR/New_Dups/missing_70.frq", delim = "\t"))
Freq
```

```{r}
# separate observed and expected n indv. to different columns
Hardy <- separate(data = Hardy, col = "OBS.HOM1.HET.HOM2.", into = c("OHom1", "OHet", "OHom2"), sep = "\\/")
Hardy <- separate(data = Hardy, col = "E.HOM1.HET.HOM2.", into = c("EHom1", "EHet", "EHom2"), sep = "\\/")
head(Hardy)
# change character to numeric
Hardy[, 3:8] <- sapply(Hardy[, 3:8], as.numeric)
head(Hardy)
```

```{r}
hwe_plot <- ggplot(Hardy, aes(P_HWE)) + geom_histogram(fill = "lightgreen", colour = "black", alpha = 0.3) + labs(title = "HWE deviation")
hwe_plot + theme_light() + geom_vline(xintercept = 0.5, colour = "red")
```

Looks like there are quite a few SNPs which deviated significantly from HWE.

```{r}
excess_plot <- ggplot(Hardy, aes(P_HET_EXCESS)) + geom_histogram(fill = "lightpink", colour = "black", alpha = 0.3) + labs(title = "Heteozygosity excess")
excess_plot + theme_light() + geom_vline(xintercept = 0.5, colour = "red")
```

```{r}
deficit_plot <- ggplot(Hardy, aes(P_HET_DEFICIT)) + geom_histogram(fill = "dodgerblue1", colour = "black", alpha = 0.3) + labs(title = "Heteozygosity deficit")
deficit_plot + theme_light() + geom_vline(xintercept = 0.5, colour = "red")
```
For a selfing population, the excess heterozygosity seems suspicious. Seems like an artefact of duplications in Arabidopsis (refer to Jaegle et al. 2023).

```{r}
Hardy$MAF <- pmin(Freq$REF_FREQ, Freq$ALT_FREQ)
Hardy$INDV <- Hardy$OHom1 + Hardy$OHet + Hardy$OHom2
Candidate <- Hardy[(Hardy$P_HET_EXCESS > 0.5), ]
```

Filter for SNPs with 17 or more samples genotyped
```{r}
# SNPs with >= 17 samples genotyped
Candidate17 <- Candidate[Candidate$INDV >= 17, ]# potential snps we can re-explore.
Candidate17
```

```{r}
# SNPs with 16 samples genotyped
Candidate16 <- Candidate[Candidate$INDV == 16, ]
Candidate16  <- Candidate16[Candidate16$P_HET_DEFICIT < Candidate16$P_HET_EXCESS, ]
Candidate16
```


```{r}
# SNPs with 15 samples genotyped
Candidate15 <- Candidate[Candidate$INDV == 15, ]
Candidate15  <- Candidate15[Candidate15$P_HET_DEFICIT < Candidate15$P_HET_EXCESS, ]
Candidate15 # still 591 SNPs here... too many to work with

# make positions file for filtering using VCFtools
Candidate15_Pos <- select(Candidate15, c(CHR, POS))
Candidate15_Pos
# write.table(Candidate15_Pos, file = "~/Desktop/THESIS PR/New_Dups/noMaxMAF/Candidate15.pos", sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)

# get list of SNPs with individual GT depths > 2 (done with VCFtools)
Filt_pos_file <- data.frame(read.table("~/Desktop/THESIS PR/New_Dups/addcov15/minDP2.pos", sep = "\t", header = TRUE))
Candidate15 <- right_join(Candidate15, Filt_pos_file, by = c("CHR", "POS"), all.y = T) #filter list of SNPs

```
